

class RepositoryException(Exception):
    ...

class CustomHTTPException(Exception):
    ...

class SMSError(Exception):
    ...

class HTTP400Exception(Exception):
    ...

class HTTP401Exception(Exception):
    ...

class HTTP403Exception(Exception):
    ...

class HTTP404Exception(Exception):
    ...

class HTTP405Exception(Exception):
    ...

class HTTP500Exception(Exception):
    ...