"""add tables user and token

Revision ID: aa9e1dc2ec70
Revises: d8faa2003dcd
Create Date: 2025-01-07 20:50:55.779771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.models.types.emailtype import EmailType


# revision identifiers, used by Alembic.
revision: str = 'aa9e1dc2ec70'
down_revision: Union[str, None] = 'd8faa2003dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', EmailType(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.Column('has_subscription', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.Enum(name="subscriptionstatus"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_active_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('token_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
