"""add user id index

Revision ID: cb4a47e3dc0f
Revises: e57799446571
Create Date: 2025-01-09 13:37:12.454891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4a47e3dc0f'
down_revision: Union[str, None] = 'e57799446571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_verificationcodes_user_id'), 'verificationcodes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verificationcodes_user_id'), table_name='verificationcodes')
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    # ### end Alembic commands ###
