"""delete col

Revision ID: b0457b758f37
Revises: 5dede0ba0767
Create Date: 2025-01-11 00:13:41.091482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0457b758f37'
down_revision: Union[str, None] = '5dede0ba0767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'type_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('type_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
