"""add verification code table, add indexes,

Revision ID: bb63d4fcb8ea
Revises: cd4c3cefe8b0
Create Date: 2025-01-09 13:33:09.811638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb63d4fcb8ea'
down_revision: Union[str, None] = 'cd4c3cefe8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_account_role'), 'users', ['account_role'], unique=False)
    op.create_index(op.f('ix_users_account_status'), 'users', ['account_status'], unique=False)
    op.create_index(op.f('ix_users_has_subscription'), 'users', ['has_subscription'], unique=False)
    op.create_index(op.f('ix_users_subscription_active_until'), 'users', ['subscription_active_until'], unique=False)
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_index(op.f('ix_users_subscription_active_until'), table_name='users')
    op.drop_index(op.f('ix_users_has_subscription'), table_name='users')
    op.drop_index(op.f('ix_users_account_status'), table_name='users')
    op.drop_index(op.f('ix_users_account_role'), table_name='users')
    # ### end Alembic commands ###
