"""create user and token tables

Revision ID: cd4c3cefe8b0
Revises: 
Create Date: 2025-01-09 12:23:32.410597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from core.models.types.emailtype import EmailType


# revision identifiers, used by Alembic.
revision: str = 'cd4c3cefe8b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('patronymic', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('email', EmailType(), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.Column('account_role', sa.Enum('DEFAULT_USER', 'ADMIN', name='accountrole'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('has_subscription', sa.Boolean(), nullable=False),
    sa.Column('subscription_status', sa.Enum('STANDARD', name='subscriptionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_active_until', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('type_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
